version: 2
jobs:
  test-electron:
    # to speed up Dockers builds turn on layer caching
    # which is a paid CircleCI feature
    # https://circleci.com/docs/2.0/docker-layer-caching/
    machine:
      docker_layer_caching: false
    steps:
    - checkout
    # to avoid long "pulling image" progress on the first time we use
    # the Docker image, pull it first
    - run: docker pull cypress/included:4.1.0
    - run:
        command: docker-compose run e2e-electron
        no_output_timeout: 3m

  test-chrome:
    machine:
      docker_layer_caching: false
    steps:
    - checkout
    - run: docker pull cypress/included:4.1.0
    - run:
        command: docker-compose run e2e-chrome
        no_output_timeout: 3m

  test-firefox:
    machine:
      docker_layer_caching: false
    steps:
    - checkout
    - run: docker pull cypress/included:4.1.0
    - run:
        command: docker-compose run e2e-firefox
        no_output_timeout: 3m

workflows:
  version: 2
  build:
    jobs:
    - test-electron
    - test-chrome
    - test-firefox
